# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vk_settings.ui'
#
# Created: Tue Oct 27 15:00:58 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(415, 355)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMouseTracking(False)
        self.gridLayout1 = QtWidgets.QGridLayout(Form)
        self.gridLayout1.setObjectName("gridLayout1")
        self.pushButtonOK = QtWidgets.QPushButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pic/apply_8900.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonOK.setIcon(icon)
        self.pushButtonOK.setIconSize(QtCore.QSize(16, 16))
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.gridLayout1.addWidget(self.pushButtonOK, 1, 0, 1, 1)
        self.pushButtonCancel = QtWidgets.QPushButton(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pic/button_cancel_9651.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCancel.setIcon(icon1)
        self.pushButtonCancel.setIconSize(QtCore.QSize(16, 16))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout1.addWidget(self.pushButtonCancel, 1, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 231, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 59, 17))
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 59, 17))
        self.label_3.setObjectName("label_3")
        self.spinRow = QtWidgets.QSpinBox(self.tab)
        self.spinRow.setGeometry(QtCore.QRect(100, 40, 44, 27))
        self.spinRow.setMinimum(2)
        self.spinRow.setMaximum(8)
        self.spinRow.setObjectName("spinRow")
        self.spinColumns = QtWidgets.QSpinBox(self.tab)
        self.spinColumns.setGeometry(QtCore.QRect(100, 80, 44, 27))
        self.spinColumns.setMinimum(2)
        self.spinColumns.setMaximum(8)
        self.spinColumns.setObjectName("spinColumns")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(210, 140, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(210, 170, 131, 33))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 170, 59, 17))
        self.label_7.setObjectName("label_7")
        self.spinPages = QtWidgets.QSpinBox(self.tab)
        self.spinPages.setGeometry(QtCore.QRect(100, 170, 44, 27))
        self.spinPages.setMinimum(2)
        self.spinPages.setMaximum(300)
        self.spinPages.setProperty("value", 3)
        self.spinPages.setObjectName("spinPages")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(17, 120, 361, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.listWidget = QtWidgets.QListWidget(self.tab_2)
        self.listWidget.setGeometry(QtCore.QRect(10, 30, 371, 191))
        self.listWidget.setObjectName("listWidget")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 111, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButtonAdd = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonAdd.setGeometry(QtCore.QRect(10, 230, 31, 27))
        self.pushButtonAdd.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pic/edit_add_1103.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAdd.setIcon(icon2)
        self.pushButtonAdd.setIconSize(QtCore.QSize(16, 16))
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.pushButtonDel = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonDel.setGeometry(QtCore.QRect(50, 230, 31, 27))
        self.pushButtonDel.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pic/edit_remove_8740.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDel.setIcon(icon3)
        self.pushButtonDel.setIconSize(QtCore.QSize(16, 16))
        self.pushButtonDel.setObjectName("pushButtonDel")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 131, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 341, 27))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.toolButton = QtWidgets.QToolButton(self.tab_3)
        self.toolButton.setGeometry(QtCore.QRect(360, 40, 22, 27))
        self.toolButton.setObjectName("toolButton")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.radioButtonNo = QtWidgets.QRadioButton(self.tab_4)
        self.radioButtonNo.setGeometry(QtCore.QRect(10, 10, 105, 22))
        self.radioButtonNo.setCheckable(True)
        self.radioButtonNo.setChecked(True)
        self.radioButtonNo.setAutoRepeat(False)
        self.radioButtonNo.setAutoExclusive(True)
        self.radioButtonNo.setObjectName("radioButtonNo")
        self.radioButtonYes = QtWidgets.QRadioButton(self.tab_4)
        self.radioButtonYes.setGeometry(QtCore.QRect(10, 40, 201, 22))
        self.radioButtonYes.setChecked(False)
        self.radioButtonYes.setObjectName("radioButtonYes")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 71, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(10, 120, 81, 17))
        self.label_10.setObjectName("label_10")
        self.spinBoxPort = QtWidgets.QSpinBox(self.tab_4)
        self.spinBoxPort.setGeometry(QtCore.QRect(100, 120, 81, 27))
        self.spinBoxPort.setMaximum(9999)
        self.spinBoxPort.setProperty("value", 3128)
        self.spinBoxPort.setObjectName("spinBoxPort")
        self.lineEditProxy = QtWidgets.QLineEdit(self.tab_4)
        self.lineEditProxy.setGeometry(QtCore.QRect(100, 80, 281, 27))
        self.lineEditProxy.setObjectName("lineEditProxy")
        self.checkBox = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox.setGeometry(QtCore.QRect(10, 160, 161, 22))
        self.checkBox.setObjectName("checkBox")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(10, 190, 59, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(10, 230, 59, 17))
        self.label_12.setObjectName("label_12")
        self.lineEditLogin = QtWidgets.QLineEdit(self.tab_4)
        self.lineEditLogin.setGeometry(QtCore.QRect(100, 190, 281, 27))
        self.lineEditLogin.setObjectName("lineEditLogin")
        self.lineEditPwd = QtWidgets.QLineEdit(self.tab_4)
        self.lineEditPwd.setGeometry(QtCore.QRect(100, 230, 281, 27))
        self.lineEditPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPwd.setClearButtonEnabled(False)
        self.lineEditPwd.setObjectName("lineEditPwd")
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout1.addWidget(self.tabWidget, 0, 0, 1, 2)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Settings"))
        self.pushButtonOK.setText(_translate("Form", "OK"))
        self.pushButtonCancel.setText(_translate("Form", "CANCEL"))
        self.label.setText(_translate("Form", "Number of rows and columns pview"))
        self.label_2.setText(_translate("Form", "Rows"))
        self.label_3.setText(_translate("Form", "Columns"))
        self.label_4.setText(_translate("Form", "Size preview"))
        self.comboBox.setItemText(0, _translate("Form", "50"))
        self.comboBox.setItemText(1, _translate("Form", "100"))
        self.comboBox.setItemText(2, _translate("Form", "130"))
        self.comboBox.setItemText(3, _translate("Form", "160"))
        self.comboBox.setItemText(4, _translate("Form", "200"))
        self.comboBox.setItemText(5, _translate("Form", "250"))
        self.label_6.setText(_translate("Form", "Pages of preview"))
        self.label_7.setText(_translate("Form", "Pages"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Preview"))
        self.label_5.setText(_translate("Form", "Vk groups view"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Groups"))
        self.label_8.setText(_translate("Form", "Path to save image"))
        self.toolButton.setText(_translate("Form", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Path"))
        self.radioButtonNo.setText(_translate("Form", "No proxy"))
        self.radioButtonYes.setText(_translate("Form", "Manual proxy configuration"))
        self.label_9.setText(_translate("Form", "Host name"))
        self.label_10.setText(_translate("Form", "Port number"))
        self.checkBox.setText(_translate("Form", "Proxy authentication"))
        self.label_11.setText(_translate("Form", "Login"))
        self.label_12.setText(_translate("Form", "Password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Proxy"))

